Changed React.PropTypes to prop-types
medlmobileenterprises/react-native-wowza-gocoder pull request #20
Opened 2017-10-20 06:08 UTC by lasuax

Since the module is moved to its own package "prop-types" this file is needed to be changed. See below: https://reactjs.org/warnings/dont-call-proptypes.html

2017-11-14 05:57 UTC, lasuax commented
@medlmichael would you review please?

2017-11-17 01:37 UTC, hugo-ns requested changes
Hi @lasuax,

Thanks for contributing to our package!
Your changes look good. For consistency purposes, could you only include the actual changes (the PropTypes to React.PropTypes - lines 97 to 109) in this PR?

2017-11-17 05:41 UTC, lasuax commented
Sure. Sorry about that, my Prettify extension does this :)

2017-11-17 06:31 UTC, lasuax commented
I've merged both changes in next PR.

2017-11-17 19:09 UTC, hugo-ns approved these changes

2017-11-17 19:10 UTC, merged