Autofocusing functionality is enabled.
medlmobileenterprises/react-native-wowza-gocoder pull request #24
Opened 2017-11-18 04:17 UTC by lasuax

2017-11-23 08:43 UTC, lasuax commented
@hugomedl Here it is.

2018-01-01 23:59 UTC, fantapop commented
@hugomedl any plans to merge this one in?

2018-01-12 00:20 UTC, hugo-ns requested changes
The changes looks good, there's just missing files that it's stopping the project to compile

2018-01-12 00:20 UTC, hugomedl commented on android/src/main/java/com/rngocoder/BroadcastView.java
> +                mAutoFocusDetector = new GestureDetectorCompat(localContext, new AutoFocusListener(localContext, cameraView));
This line file to compile, the "AutoFocusListener" class can't be find in this PR.  I assume you're using the same from the GoCoderAndroid Sdk example, please include it.

2018-01-12 00:20 UTC, hugomedl commented on android/src/main/java/com/rngocoder/BroadcastView.java
> +    private boolean autoFocus = true;
This autoFocus is not being used anywhere, it should be removed.

2018-01-12 07:37 UTC, lasuax reviewed
Added the missing class. Sorry about that.

2018-01-12 20:02 UTC, hugo-ns approved these changes

2018-01-12 20:02 UTC, merged